## Problem Statement 1:

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [2]:
#import numpy module
import numpy as np

def generate_vander_matrix(vector, no_of_columns, increasing):
    #define numpy array as input
    x = np.array(vector)
    
    start, stop, step = 0, 0, 1
    if not increasing:
        stop = no_of_columns
    else:
        start, stop, step = no_of_columns - 1, -1, -1
    print("\n")
    print("Printing in {a} order:".format(a="increasing" if increasing else "decreasing"))
    
    print(np.array([x**(no_of_columns - 1 - i) for i in range(start, stop, step)]).T)
    
    

generate_vander_matrix([1,2,3,4,5], 5, True)
generate_vander_matrix([1,2,3,4,5], 5, False)





Printing in increasing order:
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


Printing in decreasing order:
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [3]:
#other way of doing usinng list comprehention.
def Vander_matrx(vectorArr, noOfColumns,increasing = True):
    x = np.array(vectorArr)   
    N = noOfColumns
    
    if increasing:
        print(np.array([x**(N-i-1) for i in range(N-1,-1,-1)]).T)
    else:
        print(np.array([x**(N-i-1) for i in range(0,N,1)]).T)
print("Increasing order")
Vander_matrx([1,2,3,4,5],5)
print("----------------------------------------")
print("Decreasing order")
Vander_matrx([1,2,3,4,5],5,False)

Increasing order
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
----------------------------------------
Decreasing order
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


## Problem Statement 2:

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [10]:
inputarray = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
widow = 3
def movingAvg(inArray,window_size):  
   
    k =window_size
    n = len(inArray)
    movingAverageSeq = n-k+1
    
    print("the moving average sequence: {}".format((n-k+1)))
    print("\n")
    #slicing array to get moving sequence array
    array = [x for i in range(movingAverageSeq) for x in inArray[i:k+i]]
    
    print(array)
    print("\n")
    print("Reshaped array-------------------------------------------------------------------------")
    #reshapinng one dimenstional array to (movingSequencearray/windowSize, windowSize)
    reshapedArr = np.array(array).reshape(int(len(array)/k),k)
    print(reshapedArr)
    print("\n")
    print("Moving Avarages---------------------------------------------")
    print([float("{0:.2f}".format(np.array(reshapedArr[x]).mean(),2)) for x in range(movingAverageSeq)])
    
movingAvg(inputarray,widow)

the moving average sequence: 11


[3, 5, 7, 5, 7, 2, 7, 2, 8, 2, 8, 10, 8, 10, 11, 10, 11, 65, 11, 65, 72, 65, 72, 81, 72, 81, 99, 81, 99, 100, 99, 100, 150]


Reshaped array-------------------------------------------------------------------------
[[  3   5   7]
 [  5   7   2]
 [  7   2   8]
 [  2   8  10]
 [  8  10  11]
 [ 10  11  65]
 [ 11  65  72]
 [ 65  72  81]
 [ 72  81  99]
 [ 81  99 100]
 [ 99 100 150]]


Moving Avarages---------------------------------------------
[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
